### ISSUE TITLE
Kaniko can't build Kaniko image

### ISSUE THREAD

**Issue by aarongoldenthal** [chainguard-dev/kaniko#35]
**Actual behavior**

When using Google's `gcr.io/kaniko-project/executor:v1.24.0-debug` image, kaniko fails to build this project's Dockerfile at [this line](https://github.com/chainguard-dev/kaniko/blob/37afb27d847300f5baeef648b0bafcf31e35a178/deploy/Dockerfile#L67).

As a little background:
I was creating a project to build a `kaniko:debug` image from this project since no artifacts are provided (not a criticism). I had noticed that the `images` workflow in this project used Docker, but assumed that was to simplify the multiplatform build. So, I starting setting up in GitLab CI and my container build templates only use Kaniko, so I was using that for the build (of course I'd want to use kaniko to build kaniko).

Per https://github.com/GoogleContainerTools/kaniko/issues/1568, the `RUN --mount=from=busybox...` syntax is not supported and fails silently, so the image build fails with:

```sh
INFO[0207] Unpacking rootfs as cmd RUN --mount=from=busybox,dst=/usr/ ["busybox", "sh", "-c", "mkdir -p /kaniko && chmod 777 /kaniko"] requires it. 
INFO[0207] RUN --mount=from=busybox,dst=/usr/ ["busybox", "sh", "-c", "mkdir -p /kaniko && chmod 777 /kaniko"] 
INFO[0207] Initializing snapshotter ...                 
INFO[0207] Taking snapshot of full filesystem...        
INFO[0211] Cmd: busybox                                 
INFO[0211] Args: [sh -c mkdir -p /kaniko && chmod 777 /kaniko] 
INFO[0211] Running: [busybox sh -c mkdir -p /kaniko && chmod 777 /kaniko] 
error building image: error building stage: failed to execute command: starting command: exec: "busybox": executable file not found in $PATH
```

The full build log from my example project is available [here](https://gitlab.com/gitlab-ci-utils/container-images/kaniko/-/jobs/10325937766).

**Expected behavior**
The `Dockerfile` should build successfully, as it does with Docker.

**To Reproduce**
1. git clone https://github.com/chainguard-dev/kaniko.git
2. docker run --rm -it --entrypoint="" -v $(pwd):/builds -w /builds gcr.io/kaniko-project/executor:v1.24.0-debug sh (kaniko source mounted as volume since no package manager to easily install git)
3. /kaniko/executor --context ./kaniko --dockerfile ./kaniko/deploy/Dockerfile --no-push --target kaniko-debug

**Additional Information**
 - Dockerfile: as noted above, `./kaniko/deploy/Dockerfile` in this project
 - Build Context: see example above
 - Kaniko Image (fully qualified with digest): gcr.io/kaniko-project/executor:v1.24.0-debug@sha256:2562c4fe551399514277ffff7dcca9a3b1628c4ea38cb017d7286dc6ea52f4cd

 **Triage Notes for the Maintainers**
 

 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>|
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [x] </li></ul>|

**Comment by aarongoldenthal** [comment]
> Interesting question, I think dogfeeding it might be a nice little verification step. The flag is not documented in the readme, but I think passing `--kaniko-dir /kaniko2` should suffice.
> From what I can read in the code, it will automatically copy the binary from `/kaniko` over onto the `/kaniko2` upon startup and will allow you to populate the `/kaniko` dir with your own payload subsequently.

Maybe I misunderstanding, but I added that argument to the `/kaniko/executor` command I listed above and got the same error. From what I see, the mount in the line I noted is failing, so `busybox` isn't accessible.

For my case I only use the `kaniko-debug` image, so could create a different `Dockerfile` that moved commands around since `busybox` is eventually copied in for that target, but not for all. There may be some other options that work for all. My goal, though, is to just provide a build of the image as defined in the project.

**Comment by aarongoldenthal** [comment]
After a little more troubleshooting I think I understand, but a couple of issues.

As noted above, this line: https://github.com/chainguard-dev/kaniko/blob/37afb27d847300f5baeef648b0bafcf31e35a178/deploy/Dockerfile#L67

fails to mount the `busybox` image so the command, and therefore build, fails. To get around that I created a custom Dockerfile for just the `debug` build and added a command after `busybox` was copied to run `chmod`.

```Dockerfile
...
RUN ["/busybox/mkdir", "-p", "/bin"]
RUN ["/busybox/ln", "-s", "/busybox/sh", "/bin/sh"]
RUN ["/busybox/chmod", "777", "/kaniko"]
...
```

That got to the point where I needed the `--kaniko-dir /kaniko2` suggestion to get around trying to copy the new `/kaniko/executor` to the final image.

There now something locked in `/busybox`, so this line is failing: https://github.com/chainguard-dev/kaniko/blob/37afb27d847300f5baeef648b0bafcf31e35a178/deploy/Dockerfile#L108

```sh
INFO[0210] COPY --from=busybox /bin /busybox            
error building image: error building stage: failed to execute command: copying dir: creating file: open /busybox/[: text file busy
```

If there an argument to force kaniko to use a different temporary directory for the build?

**Comment by mzihlmann** [comment]
simple enough, we can just brute-force our way through the problem by adding a second debug build stage:
```Dockerfile
FROM kaniko-executor AS kaniko-debug

ENV PATH=/usr/local/bin:/kaniko:/busybox

COPY --from=builder /src/out/warmer /kaniko/warmer

COPY --from=busybox /bin /busybox
# Declare /busybox as a volume to get it automatically in the path to ignore
VOLUME /busybox

RUN ["/busybox/mkdir", "-p", "/bin"]
RUN ["/busybox/ln", "-s", "/busybox/sh", "/bin/sh"]

# same as kaniko-debug but installs busybox into /busybox2
# as /busybox is already in use when we boot into an existing
# kaniko image, and would fail during bootstrap build.
FROM kaniko-executor AS kaniko-debug-2

ENV PATH=/usr/local/bin:/kaniko:/busybox2

COPY --from=builder /src/out/warmer /kaniko/warmer

COPY --from=busybox /bin /busybox2
# Declare /busybox as a volume to get it automatically in the path to ignore
VOLUME /busybox2

RUN ["/busybox2/mkdir", "-p", "/bin"]
RUN ["/busybox2/ln", "-s", "/busybox2/sh", "/bin/sh"]
```
for the full dockerfile have a look here https://github.com/mzihlmann/kaniko/pull/59

there for sure is a clever solution too with variables etc, but as a PoC for bootstrapping this is fine. The gitlab-ci looks like this:
```yml
stages:
  - build

.build:
  stage: build
  tags:
    - linux
  script:
    - echo $DOCKER_CONFIG_JSON > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile deploy/Dockerfile
      --destination=${CI_REGISTRY_IMAGE}/bootstrap:latest
      --cache=true
      --cache-copy-layers
      --cache-dir /cache/kaniko
      --cache-repo ${CI_REGISTRY_IMAGE}/cache
      --skip-unused-stages
      $EXTRA_ARGS

bootstrap:
  extends:
    - .build
  image:
    name: martizih/kaniko:v1.24.1-debug
    entrypoint: [""]
  needs: []
  variables:
    EXTRA_ARGS: >-
      --kaniko-dir=/kaniko2
      --target=kaniko-debug-2
    KANIKO_DIR: /kaniko2

build:
  extends:
    - .build
  image:
    name: ${CI_REGISTRY_IMAGE}/bootstrap:latest
    entrypoint: [""]
  needs: [bootstrap]
  variables:
    EXTRA_ARGS: >-
      --kaniko-dir=/kaniko2
      --target=kaniko-debug
    KANIKO_DIR: /kaniko2
```

Next I will add an integration-test for bootstrapping to my kaniko fork https://github.com/mzihlmann/kaniko and try to iron out the not-so-niceties above, like needing to pass both the variable and the cli arg for kaniko-dir override.
https://github.com/GoogleContainerTools/kaniko/issues/3098
